//------------------------------------------------------------------------
// Copyright(c) 2023 jul.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"philter.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"philter VST3 (64Bit)"
#else
#define stringFileDescription	"philter VST3"
#endif
#define stringCompanyName		"jul\0"
#define stringLegalCopyright	"Copyright(c) 2023 jul."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
